programmer:
  redis:
    host: ${REDIS_HOST:127.0.0.1}
    port: ${REDIS_PORT:6379}
    password: ${REDIS_PASSWORD:}

  nacos:
    addr: ${NACOS_ADDR:127.0.0.1:8848}
    group: ${NACOS_GROUP:DEFAULT_GROUP}

springdoc:
  swagger-ui:
    path: /swagger-ui.html
