programmer:
  mysql:
    host: ${MYSQL_HOST:127.0.0.1}
    port: ${MYSQL_PORT:3306}
    user-db: ${MYSQL_USER_DB:meteor_user}
    admin-db: ${MYSQL_ADMIN_DB:meteor_admin}
    ticketing-db: ${MYSQL_TICKETING_DB:meteor_ticketing}
    movie-db: ${MYSQL_MOVIE_DB:meteor_movie}
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:}

  redis:
    host: ${REDIS_HOST:127.0.0.1}
    port: ${REDIS_PORT:6379}
    password: ${REDIS_PASSWORD:}

  nacos:
    addr: ${NACOS_ADDR:127.0.0.1:8848}

  minio:
    endpoint: ${MINIO_ENDPOINT:http://127.0.0.1:9000}
    access-key: ${MINIO_ACCESS_KEY:minioadmin}
    secret-key: ${MINIO_SECRET_KEY:minioadmin123}
    bucket: ${MINIO_BUCKET:meteor}

  rabbitmq:
    host: ${RABBIT_HOST:127.0.0.1}
    port: ${RABBIT_PORT:5672}
    vhost: ${RABBIT_VHOST:/Programmer}
    username: ${RABBIT_USERNAME:Programmer}
    password: ${RABBIT_PASSWORD:07210521}

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
